from typing import List, Dict
import os
from datetime import datetime, timezone
from src.database.mongo_client.connection import MongoConnectionManager
from src.config import MongoConfig

class AuditInspector:
    """
    The Audit Inspector analyzes raw time-series records that were
    generated by the Categorizer, and batches potentially anomalous
    or low-confidence records for human-in-the-loop verification.
    """
    def __init__(self):
        self.db = MongoConnectionManager.get_db()
        self.raw_col = self.db[MongoConfig.RAW_COLLECTION]
        
    def batch_unverified_records(self) -> List[Dict]:
        """
        Retrieves all recent categorizations that lack human-in-the-loop verification
        for presentation on the Verification Dashboard. Now sorted to highlight low-confidence items first.
        """
        # Fetch up to 10 unverified
        records = list(self.raw_col.find({"classification_verified": False}).limit(10))
        
        # Ensure ObjectId is scrubbed for JSON serialization back to the frontend
        for r in records:
             if "_id" in r:
                 r["_id"] = str(r["_id"])
                 
             # Provide default confidence if not present from legacy data
             if "confidence_score" not in r:
                 r["confidence_score"] = 0
                 
        # Sort lowest confidence first
        records.sort(key=lambda x: x["confidence_score"])
        return records

    def get_recently_verified_records(self, limit: int = 10) -> List[Dict]:
        """
        Retrieves the most recently verified records for the Dashboard ledger.
        """
        records = list(self.raw_col.find({"classification_verified": True}).sort("verification_time", -1).limit(limit))
        for r in records:
             if "_id" in r:
                 r["_id"] = str(r["_id"])
        return records

    def approve_batch(self, gcal_ids: List[str]) -> int:
        """
        Mark a batch of records as explicitly verified by the human.
        """
        result = self.raw_col.update_many(
            {"gcal_id": {"$in": gcal_ids}},
            {"$set": {"classification_verified": True, "verification_time": datetime.now(timezone.utc)}}
        )
        return result.modified_count
