from typing import List, Dict
import os
from datetime import datetime, timezone
from src.database.mongo_client.connection import MongoConnectionManager
from src.config import MongoConfig
from src.database.mongo_client.uuid_manager import UUIDGenerator

class AuditInspector:
    """
    The Audit Inspector analyzes raw time-series records that were
    generated by the Categorizer, and batches potentially anomalous
    or low-confidence records for human-in-the-loop verification.
    """
    def __init__(self):
        self.db = MongoConnectionManager.get_db()
        self.daily_col = self.db[MongoConfig.DAILY_CATEGORIZED_EVENTS]
        self.actual_col = self.db[MongoConfig.ACTUAL_COLLECTION]
        self.unified_col = self.db[MongoConfig.UNIFIED_EVENTS_COLLECTION]
        
    def batch_unverified_records(self) -> List[Dict]:
        """
        Retrieves all recent categorizations that lack human-in-the-loop verification
        for presentation on the Verification Dashboard. Now sorted to highlight low-confidence items first.
        """
        # Fetch up to 10 unverified
        records = list(self.daily_col.find({"status": "Pending Verification"}).limit(10))
        
        # Ensure ObjectId is scrubbed for JSON serialization back to the frontend
        for r in records:
             if "_id" in r:
                 r["_id"] = str(r["_id"])
                 
             # Provide default confidence if not present from legacy data
             if "confidence_score" not in r:
                 r["confidence_score"] = 0
                 
        # Sort lowest confidence first
        records.sort(key=lambda x: x["confidence_score"])
        return records

    def get_recently_verified_records(self, limit: int = 10) -> List[Dict]:
        """
        Retrieves the most recently verified records for the Dashboard ledger.
        """
        records = list(self.daily_col.find({"status": "Verified"}).sort("verification_time", -1).limit(limit))
        for r in records:
             if "_id" in r:
                 r["_id"] = str(r["_id"])
        return records

    def approve_batch(self, gcal_ids: List[str]) -> int:
        """
        Mark a batch of records as explicitly verified by the human.
        Also writes them permanently to the event_actuals ground truth collection.
        """
        records = list(self.daily_col.find({"gcal_id": {"$in": gcal_ids}, "status": "Pending Verification"}))
        modified_count = 0
        
        for r in records:
            gcal_id = r.get("gcal_id")
            event_uuid = UUIDGenerator.generate_for_event(gcal_id)
            duration_mins = r.get("duration_minutes", 60)
            
            actual_payload = {
                "title": r.get("title", "Untitled"),
                "category": r.get("pillar"),
                "energy_spent": duration_mins,
                "status": "Verified"
            }
            
            time_slot = {
                "start": r.get("start"),
                "end": r.get("end", r.get("start")) # Mock end if missing
            }
            
            # Map into Actual collection
            self.actual_col.update_one(
                {"_id": event_uuid},
                {"$set": {
                    "user_id": "hero_01",
                    "gcal_id": gcal_id,
                    "time_slot": time_slot,
                    "actual": actual_payload,
                    "metadata": {
                        "source": "verification_dashboard",
                        "last_sync": datetime.now(timezone.utc).isoformat()
                    }
                }},
                upsert=True
            )
            
            # Update Unified Collection
            self.unified_col.update_one(
                {"_id": event_uuid},
                {"$set": {
                    "actual": actual_payload
                }}
            )
            
            # Mark daily event as verified
            res = self.daily_col.update_one(
                {"_id": r["_id"]},
                {"$set": {"status": "Verified", "verification_time": datetime.now(timezone.utc)}}
            )
            modified_count += res.modified_count
            
        return modified_count
